# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'AngelHacksCaitlyn' do
	use_frameworks!
    #pod 'Alamofire'
    #pod 'SwiftyJSON', '>= 2.2'
    pod 'Parse-iOS-SDK'
    pod 'CDTDatastore'
end

target 'AngelHacksCaitlynTests' do

end

