# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'AngelHacksCaitlyn' do
	use_frameworks!
	pod 'Alamofire', '~> 1.2'
end

target 'AngelHacksCaitlynTests' do

end

